# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/aes/AWS_aes.cache/wt [current_project]
set_property parent.project_path G:/aes/AWS_aes.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/aes/AWS_aes.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/aes/verilog/qspi/QSPI_slave.v
  G:/aes/verilog/light_sensor/ad_drive.v
  G:/aes/verilog/aes_cipher_core/timescale.v
  G:/aes/verilog/aes_cipher_core/aes_cipher_top.v
  G:/aes/verilog/aes_cipher_core/aes_key_expand_128.v
  G:/aes/verilog/aes_cipher_core/aes_rcon.v
  G:/aes/verilog/aes_cipher_core/aes_sbox.v
  G:/aes/verilog/key_128test/key_128test.v
  G:/aes/verilog/light_sensor/light_sensor.v
  G:/aes/verilog/ram_count/ram_count.v
  G:/aes/AWS_aes.srcs/sources_1/new/AWS_aes_top.v
}
read_ip -quiet g:/aes/AWS_aes.srcs/sources_1/ip/blk_mem_gen_1_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all g:/aes/AWS_aes.srcs/sources_1/ip/blk_mem_gen_1_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet G:/aes/AWS_aes.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all g:/aes/AWS_aes.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet G:/aes/AWS_aes.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all g:/aes/AWS_aes.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/aes/AWS_aes.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all g:/aes/AWS_aes.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/aes/AWS_aes.srcs/constrs_1/new/AWS_aes.xdc
set_property used_in_implementation false [get_files G:/aes/AWS_aes.srcs/constrs_1/new/AWS_aes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top AWS_aes_top -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AWS_aes_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AWS_aes_top_utilization_synth.rpt -pb AWS_aes_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
